# Generated by Django 4.2.1 on 2023-06-09 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('improvements', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('praise', models.TextField(blank=True)),
                ('criticism', models.TextField(blank=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='feedbackmessage',
            constraint=models.CheckConstraint(check=models.Q(('stars__range', (1, 5))), name='starts_range'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generalMessage', to='feedback.feedbackmessage'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uiMessage', to='feedback.feedbackmessage'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ux',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uxMessage', to='feedback.feedbackmessage'),
        ),
    ]
