# Generated by Django 4.2.1 on 2023-07-04 12:53

from django.db import migrations, models
import exercises.models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["title", "tag"]},
        ),
        migrations.AlterField(
            model_name="topic",
            name="datamodel_representation",
            field=models.FileField(
                help_text="Students get the datamodel as a graphical representation of             the table structures. Upload an image preferably an svg.",
                upload_to=exercises.models.topic_path,
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="datamodel_script",
            field=models.FileField(
                help_text="This script get executed when the datamodel is being installed              or reseted.\n It must contain the DDL and insert statements for each tables.",
                upload_to=exercises.models.topic_path,
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="short",
            field=models.SlugField(
                help_text="Not translated primary key",
                max_length=10,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
